workflow: multi_source_research
version: '1.0'
description: |
  Multi-source research with parallel execution:
  Web Research + Database Query (parallel) → Synthesize

  Demonstrates parallel execution with MCP integration.
triggers:
- .*multi.*source.*
- .*comprehensive.*research.*
params:
  topic: AI frameworks
  table_name: research_data
nodes:
- web_research:
    agent: researcher
    parallel_group: sources
    instruction: Research {topic} from web sources - latest trends, tools, comparisons
    timeout: 300s
- database_query:
    agent: mcp_tool
    tool_name: query_database
    parallel_group: sources
    instruction: Query internal database for {topic} related data
    timeout: 60s
    params:
      query_payload:
        table: '{table_name}'
        method: select
        columns:
        - '*'
        limit: 100
- synthesize:
    agent: analyst
    instruction: |
      Synthesize findings from multiple sources:

      Web Research:
      {web_research}

      Database Data:
      {database_query}

      Create comprehensive analysis comparing both sources.
    depends_on:
    - web_research
    - database_query
    timeout: 180s
