workflow: sentiment_routing
version: '1.0'
description: |
  Sentiment analysis with conditional routing.

  Flow:
  1. Analyze sentiment
  2. Route based on sentiment_score:
     - High (>0.7) → positive response
     - Low (<0.3) → empathy response
     - Medium → neutral response
triggers:
- .*sentiment.*
- .*customer.*feedback.*
- .*review.*analysis.*
nodes:
- sentiment_analysis:
    agent: analyst
    instruction: |
      Analyze sentiment of this text: {user_input}

      Provide:
      1. Sentiment score (0-1)
      2. Key emotional indicators
      3. Overall tone
- positive_content:
    agent: writer
    instruction: |
      Create positive, enthusiastic response based on:
      {sentiment_analysis}
- negative_content:
    agent: writer
    instruction: |
      Create empathetic, supportive response addressing concerns from:
      {sentiment_analysis}
- neutral_content:
    agent: writer
    instruction: |
      Create balanced, informative response based on:
      {sentiment_analysis}
conditions:
- from: sentiment_analysis
  rules:
  - if: {field: sentiment_score, op: '>', value: 0.7}
    then: positive_content
  - if: {field: sentiment_score, op: <, value: 0.3}
    then: negative_content
  default: neutral_content
